### ISSUE TITLE
Payment has been sent to non existing user 

### ISSUE THREAD

**Issue by begetan** [fiatjaf/lntxbot#1]
First of all, I would like to thank for the implementation of an interesting idea and popularization of the lightning network.

Here is a real payments maid via bot. It is clear that this user probably will never apperar in Telegram chat, but sender already lost his money.
 
`1 satoshis sent to sdflkjssdljflasjdflkasdjf (couldn't notify sdflkjssdljflasjdflkasdjf as they haven't started a conversation with the bot).`

I suggest to change workflow of the bot. The best way, of course is to validate existence of the user before sending a payment, but it is hard to implement because of bot API constraints. Another way is to implement confirmation timeout around 3 or 7 days. Before that timeout receiving party should start operation with bot and get payment into his account.

If I will get all unwanted and erroronowns payments back they will be safe to send money active to wider contact list.

**Comment by fiatjaf** [comment]
I'm willing to implement a way to cancel payments made to users who haven't talked to the bot (so we don't know if they actually exist) for a lot of time. I'll do it in some days, I hope.

**Comment by fiatjaf** [comment]
This has been implemented. You can now see a "pending" icon (I think it's a clock emoji) in the `/transactions` output (you can also do `/transactions --page=2` and so on) for transactions that haven't been claimed. Then if you click on their info page directly (something like `/tx38ed0`) you should see a button to claim your satoshis back and cancel the transaction.

(I know the UI is terrible, but I really don't want to have a lot of buttons everywhere and couldn't think of a better way.)
