### ISSUE TITLE
Feature request: invoices with undefined amount

### ISSUE THREAD

**Issue by akovalenko** [fiatjaf/lntxbot#3]
In LN invoices, amount is optional: if unspecified, it's determined by sender. Lnd can generate such invoices, I'm unsure on c-lightning. Lntxbot cannot generate such invoices.

Most of the time it's not a problem, but there's a particular use case when it is: zigzag.io, when swapping from onchain to LN, rejects any invoice whose amount disagrees with its calculated value. Thus topping up lntxbot with zigzag.io becomes awfully inconvenient, especially when swapping litecoin-to-lightning, when rate is unstable.

I'd be glad if /fund or invoice without any amount just worked.

By the way, /fund 0 apparently generates a useless invoice that cannot be paid. It would better be either rejected or a synonym to unspecified amount.

**Comment by fiatjaf** [comment]
Just did that, however I have no idea of how to communicate to users that it is possible.

You can either just call `/fund` or `/invoice` or you can call `/invoice any <description>` if you want a description (`any` is a keyword for invoices of any amount).

**Comment by akovalenko** [comment]
Tested, works fine, thank you.
