### ISSUE TITLE
Feature request: fundraising by lotteries

### ISSUE THREAD

**Issue by akovalenko** [fiatjaf/lntxbot#4]
It's not something that I want to use immediately, but I believe it's such a killer feature, so I contemplating offering a bounty for it.

Let's say, /lottery n-tickets price-per-ticket percent @beneficiary -- combines "coinflip" and "fundraise" in such a way that percent% of ticket proceeds goes to beneficiary, all else goes to a single winner.

This type of fundraising is probably older than the income tax (in its modern form anyway), and it offers unique opportunity to gamble and be proud of it.

There are things that I'm unsure of, such as, should there be a time-based deadline or just cancel button available to the lottery organizer? When not enough participants show up, should the lottery be cancelled or reward be reduced? Should participant list be visible, should winner name be published? Etc.

**Comment by fiatjaf** [comment]
I like this idea as much as I like the `fundraise` idea: it's interesting, but I can't imagine anyone using it. Apparently from the server logs `coinflip` is a relative success, however `fundraise` has yet to prove itself. If `fundraise` proves itself successful this could be a good improvement to it.

**Comment by fiatjaf** [comment]
I'm unsure about adding too many variables. We should either settle on some reasonable defaults or not do it all, I think. Currently giveaways, coinflips and fundraises expire after 5 hours, however they just stay opened there until someone clicks the button and thus the "expired" message is shown. For the users balances that doesn't mean anything as no money ever leaves them until the event is settled.

**Comment by akovalenko** [comment]
I'm not expect /fundraise to become popular as it is. There's one popular use case when /tip is not enough, and /fundraise just doesn't fit well either.

Let's say, I promise to write an article if 1000000 sat is prepaid by my readers. There should be *preliminary* commitment of funds by contributors (or someone might have zero balance when it's time to settle), under the condition that if a goal is not met by the deadline, all transactions are rolled back. The amount of each contribution shouldn't be predetermined (it's okay when I donate some default unit by pressing a button, it's not okay that I can't press it 10 times to donate ten units).

While initial commitment and deadline are features, somewhat non-trivial to implement, the part about "everyone contributing equally" is just puzzling. Who wants this kind of "fairness" for real fundraising?

Lottery can be a success exactly as it's "extended coinflip". If we think of it as "extended fundraising", yes, it's doomed.

**Comment by fiatjaf** [comment]
I don't think that kind of complex feature is a good fit for a Telegram bot, then.

However, that's exactly the kind of use-case for which I wrote https://etleneum.com/. I was even considering writing a bot that was able to call generic Etleneum contracts as soon as the service had more users.

Even more specific to your example of people prepaying for some task I was working on an Etleneum contract with the provisory name of "Somebody Make This" and accompanying graphical interface client. The source code for the contract is on the site, the client is in the works, but if you're interested, please beat me to it!
